# Generated by Django 2.2 on 2020-02-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requests',
            table='Requests',
        ),
    ]
